### ISSUE TITLE
remove `Properties(['uniform-sampling'])` requirement for alpha/beta/alpha-phylogenetic/beta-phylogenetic methods

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-diversity#110]
It would be nice if we could make the beta diversity input types more flexible.

For instance, some distance metrics that operate directly on proportions can perform better when working with the raw counts.  In addition, jackknifing / bootstrapping is best applied to the raw counts.

**Comment by jairideout** [comment]
Can you describe what types of input you'd like `qiime diversity beta` and/or `qiime diversity beta-phylogenetic` to support? Right now they support an input of `FeatureTable[Frequency]`, which is a table of raw counts (both examples you listed seem to be satisfied with the currently supported input type).

Is it the `Properties(['uniform-sampling'])` requirement that you'd like to see relaxed? Maybe I'm misunderstanding what you mean by "raw counts".

**Comment by mortonjt** [comment]
@jairideout you nailed it.  It would be nice if `Properties(['uniforming-sampling'])` could be relaxed.  Right now, if I wanted to run beta diversity metrics on a `FeatureTable[Frequency]` that isn't normalized, I'd need to force the type into `FeatureTable[Frequency] % Properties(['uniform-sampling'])`

**Comment by ebolyen** [comment]
@mortonjt, wouldn't a jacknifing/bootstrapping situation require a new method anyhow? It would be free to accept any input it wanted. As for proportional metrics, maybe there needs to be more granular methods with different specific requirements on input instead of a catch-all that passes through to skbio/scipy.

Another thought:
Would being able to override the type (flagging a warning in provenance) suite your purpose? In other-words QIIME 2 would just match on the view-type and as long as a transformer existed would permit the operation while complaining about how much it doesn't like what is happening. 

This is an escape-hatch that has been on the backburner for a long time, but I think we kind of anticipated that some people may need to escape the safety of the semantic types in certain situations.

**Comment by gregcaporaso** [comment]
Just discussed this with @antgonza and @rob-knight. I'll work on this for this release.
