### ISSUE TITLE
Export data from beta_group_significance

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-diversity#135]
This came up on [the forum](https://forum.qiime2.org/t/link-to-raw-data-behind-figures/650/4?u=thermokarst).

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/beta-group-significance/3365)

**Comment by mestaki** [comment]
Just a thought, the original request for this item -and a few others like this- was to have access to the raw distance values. Instead of (or additional to) adding a download option in the visualizer itself, perhaps there can be an added option in the original distance-calculation artifact step to also print out the csv-format distances. ex. --o-rawdata TRUE, basically replacing the need for exporting separately. Certainly a convenient thing only.
