### ISSUE TITLE
Number of threads exceeds samples

### ISSUE THREAD

**Issue by sjanssen2** [qiime2/q2-diversity#166]
**Bug Description**
`qiime diversity beta-phylogenetic-alt --i-table input.qza --i-phylogeny reference_tree.qza --p-metric unweighted_unifrac --p-n-jobs 10 --o-distance-matrix unweighted_unifrac`

Fails with the following misleading error when there are to few samples in input.gza to be properly parallelized. "input.gza" had only 10 samples in this case.

**Screenshots**
```
Plugin error from diversity:

  Data must be symmetric and cannot contain NaNs.

See above for debug info.
```

**References**
**A follow up from #165**

**Comment by ChrisKeefe** [comment]
Closing. The fix is upstream in `unifrac`, which I believe reports the issue to stderror but carries on gracefully. `q2-diversity-lib` also has a [test](https://github.com/qiime2/q2-diversity-lib/blob/e6a149d408a6c11bcf6f8e66f10f93daa835d83a/q2_diversity_lib/tests/test_util.py#L196) rigged up to catch misbehavior.

![image](https://user-images.githubusercontent.com/39198770/90300674-8e0a2180-de50-11ea-82d0-36ba251d2c0f.png)

**Comment by thermokarst** [comment]
The screenshot doesn't mention anything about the sample count, which as I understand, is the critical component of this error (fewer samples than cpus/threads requested). Can you clarify, is the sample < thread case what was addressed in unifrac package?

**Comment by thermokarst** [comment]
Also, can you xref the closing pr here?

**Comment by ChrisKeefe** [comment]
@thermokarst, the [table under test](https://github.com/qiime2/q2-diversity-lib/blob/master/q2_diversity_lib/tests/data/two_feature_table.biom) in the screenshot and above has three samples.  

I'm not clear on how things in `unifrac` are wired together, but I _think_ these three bits ([1](https://github.com/biocore/unifrac/blob/77a0692c1fc265214f7bee9349b20527d332e239/sucpp/api.cpp#L260), [2](https://github.com/biocore/unifrac/blob/77a0692c1fc265214f7bee9349b20527d332e239/sucpp/api.cpp#L312), [3](https://github.com/biocore/unifrac/blob/77a0692c1fc265214f7bee9349b20527d332e239/sucpp/api.cpp#L821)) handle the issue. ([PR](https://github.com/biocore/unifrac/pull/43))

I'm basing this belief primarily on my inability to reproduce the result in the screenshot. The PR I think fixed this was merged but not released at the time this issue was created, so I'm assuming @sjanssen2 found the bug in an official release version (0.9.3, maybe) and not the development version current at the time.

Timeline, in case it's relevant: 

1. 9/22/17   Release 0.9.3          https://github.com/biocore/unifrac/releases
2. 10/5/17    PR #43                    https://github.com/biocore/unifrac/pull/43
3. 11/6/17    issue posted         https://github.com/qiime2/q2-diversity/issues/166
4. 7/08/19  Release 0.10.0    https://github.com/biocore/unifrac/releases

**Comment by thermokarst** [comment]
Great, thanks for explaining, @ChrisKeefe!
