### ISSUE TITLE
beta-group-significance funny business with sample sizes

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-diversity#52]
Possibly related to [this issue](https://github.com/qiime2/q2-diversity/issues/37)

``beta-group-significance`` is doing some goofy things with reporting sample sizes (and hence possibly calculations that depend on these).

This dataset should contain 37 samples: 35 stool, 1 plasma, and 1 colon tissue. In [Stool-boxplots.pdf](https://github.com/qiime2/q2-diversity/files/534418/Stool-boxplots.pdf), "Stool" lists 595 stool samples and 35 each for the other categories. The other samples also show a distribution of distances (rather than a single bar as should occur when N = 1). In [Plasma-boxplots.pdf](https://github.com/qiime2/q2-diversity/files/534419/Plasma-boxplots.pdf), when the sample size of any group == 1, that sample size drops to 0 in comparison plots, though the other groups show the correct sample sizes.

This is obviously causing the wrong distribution to be plotted and — more worrying — possibly the PERMANOVA calculations.

**Comment by gregcaporaso** [comment]
@nbokulich, could you email me the input files that you're providing? Thanks!

**Comment by gregcaporaso** [comment]
@nbokulich, I'm pretty sure that these are correct. The sample size being reported here is the number of pairwise distances that are in each distribution. 

So, in `Stool-boxplots.pdf`, the number of stool to stool distances is `(n * (n - 1)) / 2`, or `(35 * 34) / 2` (because each of the 35 stool samples is compared to the 34 other stool samples, and we then only consider half of those values since the distances are symmetric). Since there is only a single sample in the other groups, the number of distances in the distribution is `1 * 35` in both cases. 

In `Plasma-boxplots.pdf`, since there is only one plasma sample there are zero within-group distances `(1 * 0) / 2`, and there is one colon tissue to plasma distance and 35 stool to plasma distances. 

Does that make sense? Do you think there should be documentation of this in the visualization.

**Comment by nbokulich** [comment]
Ah of course — a lapse in my judgement. I had forgotten that these would be pairwise distances, not sample count. Sorry for the false report!

**Comment by gregcaporaso** [comment]
No problem!
